pg_config:
  DB_HOST: "db"
#  DB_HOST: "localhost"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_NAME: "postgres"
  DB_PASSWORD: "pass"
  SSL_MODE: "disable"

app_config:
  APP_MODE: "prod"
  APP_HOST: "0.0.0.0"
  APP_PORT: "8080"
  USER: "User"
