pg_config:
  DB_HOST: "${DB_HOST}"
  DB_PORT: "${DB_PORT}"
  DB_USER: "${DB_USER}"
  DB_NAME: "${DB_NAME}"
  DB_PASSWORD: "${DB_PASSWORD}"
  SSL_MODE: "${DB_SSL_MODE}"

app_config:
  APP_MODE: "${APP_MODE}"
  APP_HOST: "${APP_LISTEN_HOST}"
  APP_PORT: "${APP_LISTEN_PORT}"

log_config:
  LEVEL: "${LEVEL}"  # Возможные значения: debug, info, warn, error
  FORMAT: "${FORMAT}"  # Возможные значения: json, text
  ADD_SOURCE: "${ADD_SOURCE}" # Возможные значения: false, true