name: Deploy to Beget via FTP

on:
  push:
    branches:
      - main  # Или любая другая ветка для деплоя

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go environment
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Run go mod tidy
        run: go mod tidy

      - name: Run Golangci-lint
        uses: golangci/golangci-lint-action@v6.0.1

      - name: Set up Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Build project
        run: go build -o myapp

      - name: Deploy to Beget via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: build  # Директория, которую вы хотите загрузить
          server-dir: /  # Путь на сервере, куда нужно загрузить файлы