name: Deploy to Server via SSH

on:
  push:
    branches:
      - main  # Or whichever branch to deploy from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      HOST: root@87.228.12.165  # Update to your server's user@IP
      DEPLOY_DIRECTORY: /root/apps/base-api
      CONFIG_PATH: /root/apps/base-api/configs/prod.yml
      ENV_FILE_PATH: /root/apps/base-api/config.env

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go environment
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Run lint and tests
        run: |
          go mod tidy
          golangci-lint run

      - name: Build the Go project
        run: go build -o build/base-api ./cmd/api

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Transfer files via SSH
        run: |
          scp -r build/base-api ${{ env.HOST }}:${{ env.DEPLOY_DIRECTORY }}/
          scp docker-compose.yml ${{ env.HOST }}:${{ env.DEPLOY_DIRECTORY }}/
          scp -r configs ${{ env.HOST }}:${{ env.DEPLOY_DIRECTORY }}/

      - name: Deploy via SSH
        run: |
          ssh ${{ env.HOST }} << 'EOF'
            cd ${{ env.DEPLOY_DIRECTORY }}
            docker-compose down
            docker-compose up -d --build
          EOF