name: Lint and Generate Docs

on:
  push:
    branches:
      - main  # Или другая ветка, где нужно запускать задачи

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go environment
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Run go mod tidy
        run: go mod tidy

      - name: Run Golangci-lint
        uses: golangci/golangci-lint-action@v6.0.1

  check-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go environment
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Install swag
        run: go install github.com/swaggo/swag/cmd/swag@latest

      - name: Generate Swagger Documentation
        run: swag init -g cmd/api/main.go -o ./docs --parseInternal

      - name: Check for documentation changes
        run: |
          if [ -n "$(git status --porcelain ./docs)" ]; then
            echo "Swagger documentation is outdated. Please run 'swag init' locally and commit the changes."
            exit 1
          fi