name: Deploy with Docker Compose to Vercel

on:
  push:
    branches:
      - main  # Или любая другая ветка для деплоя

env:
  COMPOSE_PROJECT_NAME: ${{ secrets.COMPOSE_PROJECT_NAME }}
  DB_EXTERNAL_PORT: ${{ secrets.DB_EXTERNAL_PORT }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_NAME: ${{ secrets.DB_NAME }}
  API_EXTERNAL_PORT: ${{ secrets.API_EXTERNAL_PORT }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go environment
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Run go mod tidy
        run: go mod tidy

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker images
        run: docker-compose -f docker-compose.yml build

      - name: Push Docker images
        run: docker-compose -f docker-compose.yml push

      - name: Run Docker Compose
        run: docker-compose -f docker-compose.yml up -d

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: vercel --prod --token $VERCEL_TOKEN