name: Deploy

on:
  push:
    branches:
      - main  # Или любая другая ветка для деплоя

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go environment
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Run go mod tidy
        run: go mod tidy

      - name: Run Golangci-lint
        uses: golangci/golangci-lint-action@v6.0.1

      - name: Build project
        run: go build -o build/base-api ./cmd/api

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: build/

  deploy:
    needs: lint-and-build
    runs-on: ubuntu-latest
    env:
      HOST: root@87.228.12.165
      DEPLOY_DIRECTORY: /root/apps/base-api
#      CONFIG_PATH: /root/apps/base-api/configs/какой-то.yml
#      ENV_FILE_PATH: /root/apps/base-api/config.env

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Check disk usage before deploy
        run: df -h

      - name: Clean Docker
        run: docker system prune -af --volumes

      - name: Drop system caches
        run: echo 3 | sudo tee /proc/sys/vm/drop_caches

      - name: Create remote directory and transfer files
        run: |
          ssh -o StrictHostKeyChecking=no ${{ env.HOST }} "mkdir -p ${{ env.DEPLOY_DIRECTORY }}"
          scp -o StrictHostKeyChecking=no -r * ${{ env.HOST }}:${{ env.DEPLOY_DIRECTORY }}/

      - name: Create .env file
        run: | 
          ssh -o StrictHostKeyChecking=no ${{ env.HOST }} << EOF
            echo 'COMPOSE_PROJECT_NAME=base-api-backend' > ${{ env.DEPLOY_DIRECTORY }}/.env
            echo 'DB_EXTERNAL_PORT=${{ secrets.DB_EXTERNAL_PORT }}' >> ${{ env.DEPLOY_DIRECTORY }}/.env
            echo 'DB_USER=${{ secrets.DB_USER }}' >> ${{ env.DEPLOY_DIRECTORY }}/.env
            echo 'DB_PASSWORD=${{ secrets.DB_PASSWORD }}' >> ${{ env.DEPLOY_DIRECTORY }}/.env
            echo 'DB_NAME=${{ secrets.DB_NAME }}' >> ${{ env.DEPLOY_DIRECTORY }}/.env
            echo 'API_EXTERNAL_PORT=${{ secrets.API_EXTERNAL_PORT }}' >> ${{ env.DEPLOY_DIRECTORY }}/.env
            echo 'APP_MODE=prod' >> ${{ env.DEPLOY_DIRECTORY }}/.env
            echo 'APP_LISTEN_HOST=0.0.0.0' >> ${{ env.DEPLOY_DIRECTORY }}/.env
            echo 'APP_LISTEN_PORT=8080' >> ${{ env.DEPLOY_DIRECTORY }}/.env
            echo 'DB_HOST=base-api-backend-db' >> ${{ env.DEPLOY_DIRECTORY }}/.env
            echo 'DB_PORT=5432' >> ${{ env.DEPLOY_DIRECTORY }}/.env
            echo 'DB_SSL_MODE=disable' >> ${{ env.DEPLOY_DIRECTORY }}/.env
          EOF
      

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ env.HOST }} << 'EOF'
            cd ${{ env.DEPLOY_DIRECTORY }}
            chmod +x scripts/set_config.sh
            ./scripts/set_config.sh
            docker-compose down
            DOCKER_BUILDKIT=1 COMPOSE_DOCKER_CLI_BUILD=1 docker-compose build --no-cache --progress=plain --build-arg BUILDKIT_PROGRESS=plain --build-arg BUILDKIT_PARALLELISM=2
            docker-compose up -d
          EOF

      - name: Check disk usage after deploy
        run: df -h